// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Flow3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void flow3() {
    driver.get("http://localhost/Assign%203/authenticate.php");
    driver.manage().window().setSize(new Dimension(1550, 878));
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("user1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("user1");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#\\\'cs5302\\\' > p:nth-child(2) > b")).click();
    driver.findElement(By.cssSelector("#cs5302 .w3-button")).click();
    driver.findElement(By.id("search")).click();
    driver.findElement(By.id("search")).sendKeys("cs");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("CS 5330")).click();
    vars.put("win6318", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win6318").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.id("search")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Profile")).click();
    vars.put("win9489", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9489").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.name("namestud")).click();
    driver.findElement(By.name("namestud")).sendKeys("user1");
    driver.findElement(By.name("semadmit")).click();
    driver.findElement(By.name("semadmit")).sendKeys("fall 2019");
    driver.findElement(By.name("antgrad")).click();
    driver.findElement(By.name("antgrad")).sendKeys("may 2021");
    driver.findElement(By.cssSelector("div:nth-child(5) tr:nth-child(2) > td:nth-child(1) > input")).click();
    driver.findElement(By.name("elec1")).click();
    {
      WebElement dropdown = driver.findElement(By.name("elec1"));
      dropdown.findElement(By.xpath("//option[. = 'CS6307 - Introduction to Big Data Management and Analytics']")).click();
    }
    driver.findElement(By.name("elec1")).click();
    driver.findElement(By.name("elec3")).click();
    {
      WebElement dropdown = driver.findElement(By.name("elec3"));
      dropdown.findElement(By.xpath("//option[. = 'CS6331 - Multimedia Systems']")).click();
    }
    driver.findElement(By.name("elec3")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) tr:nth-child(4) > td:nth-child(1)")).click();
    driver.findElement(By.name("elec4")).click();
    driver.findElement(By.name("elec4")).click();
    {
      WebElement dropdown = driver.findElement(By.name("elec4"));
      dropdown.findElement(By.xpath("//option[. = 'CS6321 - Discourse Processing']")).click();
    }
    driver.findElement(By.name("elec4")).click();
    driver.findElement(By.name("elec5")).click();
    {
      WebElement dropdown = driver.findElement(By.name("elec5"));
      dropdown.findElement(By.xpath("//option[. = 'CS6328 - Modeling and Simulation']")).click();
    }
    driver.findElement(By.name("elec5")).click();
    driver.findElement(By.name("elec6")).click();
    {
      WebElement dropdown = driver.findElement(By.name("elec6"));
      dropdown.findElement(By.xpath("//option[. = 'CS6315 - Semantic Web']")).click();
    }
    driver.findElement(By.name("elec6")).click();
    driver.findElement(By.name("prereq1")).click();
    driver.findElement(By.name("prereq2")).click();
    driver.findElement(By.cssSelector("div:nth-child(8) tr:nth-child(3) > td:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div:nth-child(8) tr:nth-child(3) > td:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div:nth-child(8) tr:nth-child(3) > td:nth-child(1)")).click();
    driver.findElement(By.name("prereq3")).click();
    driver.findElement(By.name("prereq4")).click();
    driver.findElement(By.name("prereq5")).click();
    driver.findElement(By.name("prereq6")).click();
    driver.findElement(By.name("submit")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Case1 user1 2020-04-05 06:57:46pm")).click();
    vars.put("win6137", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6137").toString());
    driver.findElement(By.name("row8grade")).click();
    driver.findElement(By.name("row8grade")).sendKeys("A");
    driver.findElement(By.name("update")).click();
    driver.findElement(By.linkText("Case1 user1 2020-04-05 07:28:53pm")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".myPageLogout > button:nth-child(2)")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
